"""added_private_link

Revision ID: 263b0145764c
Revises: 94152c297342
Create Date: 2025-06-15 17:38:47.326286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263b0145764c'
down_revision: Union[str, None] = '94152c297342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('private_link_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_interviews_private_link_token'), 'interviews', ['private_link_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_private_link_token'), table_name='interviews')
    op.drop_column('interviews', 'private_link_token')
    # ### end Alembic commands ###
